/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 16
#line 1 "ekipp-defn.grm.leg"

#define YYSTYPE wchar_t*
#define YYPARSE	yydefparse

#define YY_CTX_LOCAL

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <wchar.h>

#include <gc.h>

extern wchar_t* yybuiltineval(wchar_t*);
extern wchar_t* yybodyeval(wchar_t*);
extern FILE*	yyin;
extern FILE*  	yyout;

wchar_t* yydefeval(wchar_t*);

#define yyrelease 	yyrls
#define yyparsefrom	yypfm

#include "ekipp.h"

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_COMMENT(yycontext *yy); /* 16 */
YY_RULE(int) yy_SPACE(yycontext *yy); /* 15 */
YY_RULE(int) yy_EOL(yycontext *yy); /* 14 */
YY_RULE(int) yy_DEFN(yycontext *yy); /* 13 */
YY_RULE(int) yy__(yycontext *yy); /* 12 */
YY_RULE(int) yy_ARG(yycontext *yy); /* 11 */
YY_RULE(int) yy_Args(yycontext *yy); /* 10 */
YY_RULE(int) yy_IDENT(yycontext *yy); /* 9 */
YY_RULE(int) yy_Define(yycontext *yy); /* 8 */
YY_RULE(int) yy_Defeval(yycontext *yy); /* 7 */
YY_RULE(int) yy_Push(yycontext *yy); /* 6 */
YY_RULE(int) yy_Pusheval(yycontext *yy); /* 5 */
YY_RULE(int) yy_undef(yycontext *yy); /* 4 */
YY_RULE(int) yy_pop(yycontext *yy); /* 3 */
YY_RULE(int) yy_Call(yycontext *yy); /* 2 */
YY_RULE(int) yy_DefMain(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_IDENT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_IDENT\n"));
  {
#line 70
   __ = gc_mbsdup(&yytext[0]); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_DEFN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DEFN\n"));
  {
#line 65
   __ = gc_mbsdup(&yytext[0]);  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_ARG(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ARG\n"));
  {
#line 63
   __ = gc_mbsdup(&yytext[0]); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Define(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Define\n"));
  {
#line 59
   
					 insert_symbol(i, d);        ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
#undef i
}
YY_ACTION(void) yy_1_Defeval(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Defeval\n"));
  {
#line 55
   
				insert_symbol(i, yybuiltineval(d));  ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
#undef i
}
YY_ACTION(void) yy_1_Push(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Push\n"));
  {
#line 51
   
					push_stack(i, d);   ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
#undef i
}
YY_ACTION(void) yy_1_Pusheval(yycontext *yy, char *yytext, int yyleng)
{
#define d yy->__val[-1]
#define i yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Pusheval\n"));
  {
#line 47
   
				push_stack(i, yybuiltineval(d));     ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef d
#undef i
}
YY_ACTION(void) yy_1_undef(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_undef\n"));
  {
#line 45
   remove_symbol(i);	      ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
}
YY_ACTION(void) yy_1_pop(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_pop\n"));
  {
#line 41
   pop_stack();		      ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_Args(yycontext *yy, char *yytext, int yyleng)
{
#define a yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Args\n"));
  {
#line 38
   invoke_addarg(a);	      ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef a
}
YY_ACTION(void) yy_1_Call(yycontext *yy, char *yytext, int yyleng)
{
#define i yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_Call\n"));
  {
#line 35
   invoke_macro(i);	      ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef i
}

YY_RULE(int) yy_COMMENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COMMENT"));  if (!yymatchChar(yy, '#')) goto l1;
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yy_EOL(yy)) goto l2;  goto l1;
  l2:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;
  }  if (!yymatchDot(yy)) goto l1;  if (!yy_EOL(yy)) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "COMMENT", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COMMENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SPACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SPACE"));
  {  int yypos4= yy->__pos, yythunkpos4= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l5;  goto l4;
  l5:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yymatchChar(yy, '\t')) goto l6;  goto l4;
  l6:;	  yy->__pos= yypos4; yy->__thunkpos= yythunkpos4;  if (!yy_EOL(yy)) goto l3;
  }
  l4:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 1;
  l3:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;
  l8:;	
  {  int yypos9= yy->__pos, yythunkpos9= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\044\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos9; yy->__thunkpos= yythunkpos9;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DEFN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DEFN"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l10;
#undef yytext
#undef yyleng
  }
  l11:;	
  {  int yypos12= yy->__pos, yythunkpos12= yy->__thunkpos;
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yy_EOL(yy)) goto l13;  if (!yy_EOL(yy)) goto l13;  goto l12;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }  if (!yymatchDot(yy)) goto l12;  goto l11;
  l12:;	  yy->__pos= yypos12; yy->__thunkpos= yythunkpos12;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l10;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_DEFN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DEFN", yy->__buf+yy->__pos));
  return 1;
  l10:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DEFN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l15:;	
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yy_SPACE(yy)) goto l18;  goto l17;
  l18:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;  if (!yy_COMMENT(yy)) goto l16;
  }
  l17:;	  goto l15;
  l16:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_ARG(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ARG"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l19;
#undef yytext
#undef yyleng
  }
  {  int yypos22= yy->__pos, yythunkpos22= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l22;  goto l19;
  l22:;	  yy->__pos= yypos22; yy->__thunkpos= yythunkpos22;
  }  if (!yymatchDot(yy)) goto l19;
  l20:;	
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;
  {  int yypos23= yy->__pos, yythunkpos23= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l23;  goto l21;
  l23:;	  yy->__pos= yypos23; yy->__thunkpos= yythunkpos23;
  }  if (!yymatchDot(yy)) goto l21;  goto l20;
  l21:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l19;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_ARG, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ARG", yy->__buf+yy->__pos));
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ARG", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Args(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Args"));  if (!yy_ARG(yy)) goto l24;  yyDo(yy, yySet, -1, 0);
  {  int yypos27= yy->__pos, yythunkpos27= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l27;  goto l28;
  l27:;	  yy->__pos= yypos27; yy->__thunkpos= yythunkpos27;
  }
  l28:;	
  l25:;	
  {  int yypos26= yy->__pos, yythunkpos26= yy->__thunkpos;  if (!yy_ARG(yy)) goto l26;  yyDo(yy, yySet, -1, 0);
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchChar(yy, ',')) goto l29;  goto l30;
  l29:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }
  l30:;	  goto l25;
  l26:;	  yy->__pos= yypos26; yy->__thunkpos= yythunkpos26;
  }  yyDo(yy, yy_1_Args, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Args", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l24:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Args", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_IDENT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "IDENT"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l31;
  l32:;	
  {  int yypos33= yy->__pos, yythunkpos33= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l33;  goto l32;
  l33:;	  yy->__pos= yypos33; yy->__thunkpos= yythunkpos33;
  }  yyDo(yy, yy_1_IDENT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IDENT", yy->__buf+yy->__pos));
  return 1;
  l31:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IDENT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Define(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Define"));  if (!yymatchString(yy, "@!")) goto l34;  if (!yy__(yy)) goto l34;  if (!yymatchString(yy, "define")) goto l34;  if (!yy__(yy)) goto l34;  if (!yymatchChar(yy, '$')) goto l34;  if (!yy__(yy)) goto l34;  if (!yy_IDENT(yy)) goto l34;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l34;  if (!yy_DEFN(yy)) goto l34;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l34;  yyDo(yy, yy_1_Define, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Define", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l34:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Define", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Defeval(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Defeval"));  if (!yymatchString(yy, "@!")) goto l35;  if (!yy__(yy)) goto l35;  if (!yymatchString(yy, "defeval")) goto l35;  if (!yy__(yy)) goto l35;  if (!yymatchChar(yy, '$')) goto l35;  if (!yy__(yy)) goto l35;  if (!yy_IDENT(yy)) goto l35;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l35;  if (!yy_DEFN(yy)) goto l35;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l35;  yyDo(yy, yy_1_Defeval, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Defeval", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Defeval", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Push(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Push"));  if (!yymatchString(yy, "@!")) goto l36;  if (!yy__(yy)) goto l36;  if (!yymatchString(yy, "push")) goto l36;  if (!yy__(yy)) goto l36;  if (!yymatchChar(yy, '$')) goto l36;  if (!yy__(yy)) goto l36;  if (!yy_IDENT(yy)) goto l36;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l36;  if (!yy_DEFN(yy)) goto l36;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l36;  yyDo(yy, yy_1_Push, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Push", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Push", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Pusheval(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Pusheval"));  if (!yymatchString(yy, "@!")) goto l37;  if (!yy__(yy)) goto l37;  if (!yymatchString(yy, "pusheval")) goto l37;  if (!yy__(yy)) goto l37;  if (!yymatchChar(yy, '$')) goto l37;  if (!yy__(yy)) goto l37;  if (!yy_IDENT(yy)) goto l37;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l37;  if (!yy_DEFN(yy)) goto l37;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l37;  yyDo(yy, yy_1_Pusheval, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Pusheval", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l37:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Pusheval", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_undef(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "undef"));  if (!yymatchString(yy, "@!")) goto l38;  if (!yy__(yy)) goto l38;  if (!yymatchString(yy, "undef")) goto l38;  if (!yy__(yy)) goto l38;  if (!yymatchChar(yy, '$')) goto l38;  if (!yy__(yy)) goto l38;  if (!yy_IDENT(yy)) goto l38;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l38;  yyDo(yy, yy_1_undef, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "undef", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l38:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "undef", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_pop(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "pop"));  if (!yymatchString(yy, "@!")) goto l39;  if (!yy__(yy)) goto l39;  if (!yymatchString(yy, "pop")) goto l39;  yyDo(yy, yy_1_pop, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "pop", yy->__buf+yy->__pos));
  return 1;
  l39:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "pop", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_Call(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "Call"));  if (!yymatchChar(yy, '$')) goto l40;  if (!yy_IDENT(yy)) goto l40;  yyDo(yy, yySet, -1, 0);
  {  int yypos41= yy->__pos, yythunkpos41= yy->__thunkpos;  if (!yymatchChar(yy, '(')) goto l41;  if (!yy_Args(yy)) goto l41;  if (!yymatchChar(yy, ')')) goto l41;  goto l42;
  l41:;	  yy->__pos= yypos41; yy->__thunkpos= yythunkpos41;
  }
  l42:;	  yyDo(yy, yy_1_Call, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Call", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l40:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Call", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DefMain(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DefMain"));
  l44:;	
  {  int yypos45= yy->__pos, yythunkpos45= yy->__thunkpos;
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yy_Call(yy)) goto l47;  goto l46;
  l47:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_pop(yy)) goto l48;  goto l46;
  l48:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_undef(yy)) goto l49;  goto l46;
  l49:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Pusheval(yy)) goto l50;  goto l46;
  l50:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Push(yy)) goto l51;  goto l46;
  l51:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Defeval(yy)) goto l52;  goto l46;
  l52:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_Define(yy)) goto l45;
  }
  l46:;	  goto l44;
  l45:;	  yy->__pos= yypos45; yy->__thunkpos= yythunkpos45;
  }  if (!yymatchString(yy, "\x00")) goto l43;
  yyprintf((stderr, "  ok   %s @ %s\n", "DefMain", yy->__buf+yy->__pos));
  return 1;
  l43:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DefMain", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_DefMain);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 74 "ekipp-defn.grm.leg"


#define RET_MAX		65536

wchar_t* yydefeval(wchar_t* code) {
	FILE* inhold 	= stdin;
	FILE* outhold   = stdout;

	wchar_t* ret	= GC_MALLOC(RET_MAX * sizeof(wchar_t));

	stdin		= fmemopen(code, wcslen(code), "r");
	stdout		= fmemopen(ret, RET_MAX * sizeof(wchar_t), "w");

	yycontext ctx;
        memset(&ctx, 0, sizeof(ctx));

	while (yydefparse(&ctx));

	fclose(stdin);
	fclose(stdout);

	stdin		= inhold;
	stdout		= outhold;

	return ret;
}


